### ISSUE TITLE
Error: write EPIPE

### ISSUE THREAD

**Issue by Guss42** [amir20/phantomjs-node#475]
### Expected behavior

exept this output from the function wrtiten later in this issue

```
ph created
page created
page opened: success
page evaluated
```

### Actual behavior

```
debug: Starting /usr/lib/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs /home/admin/ipchecker/node_modules/phantom/lib/shim.js
ph created
debug: Sending: {"id":"e6c435f5c8fa277d373d1a8fe986872b","target":"phantom","name":"createPage","params":[],"deferred":{"resolve":"function () { [native code] }","reject":"function () { [native code] }"}}
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:953:11)
    at WriteWrap.afterWrite (net.js:793:14)
```

### Steps to reproduce the behavior
use this function:

```
function requestPage(pageAddress){
	var data = Q.defer();
	phc.create().then(function(ph){
		console.log("ph created");
		ph.createPage(ph).then(function(page){
			console.log("page created");
			page.open(pageAddress).then(function(obj){
				console.log("page opened:", obj);
				if( obj == "success" ){
					page.evaluate(function(){
						return document.body.innerHTML;
					}).then(function(d){
						console.log("page evaluated");
						page.close();
						ph.exit();
						data.resolve(d);
					});
				}
				else {
					page.close();
					ph.exit();
					data.reject(obj);
				}
			}).catch(function(e){
				console.error(pageAddress, ": ", e);
				ph.exit();
				data.reject(e);
			});
		}).catch(function(e){
			console.error(pageAddress, ": ", e);
			ph.exit();
			data.reject(e);
		});
	});
	return data.promise;
}
```

### Environment

- OS: working on archlinux, not working on debian jessie
- Node version (`node -v`): 6.2.0
- package version: 2.1.2

**Comment by amir20** [comment]
This sounds like a problem with phantomjs. I don't have `events.js`.

**Comment by Guss42** [comment]
I have last version of phantomjs (phantomjs-prebuilt package from npm)

**Comment by amir20** [comment]
Again, this seems to be related to phantomjs and not this module. It doesn't matter if you have latest prebuilt. `events.js` isn't part of this package.
