### ISSUE TITLE
Creating two Phantom instances with GhostDriver and then exiting both, should not throw exceptions

### ISSUE THREAD

**Issue by compulim** [amir20/phantomjs-node#491]
### Expected behavior

Create a new Phantom instance with GhostDriver arguments, then exiting it. Do it twice. It should complete and kill both processes successfully.

### Actual behavior

When calling `phantom.exit()` for the 2nd instance, it throws the following exception:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:285:12)
    at Phantom.executeCommand (webdriver\node_modules\phantom\lib\phantom.js:219:32)
    at Phantom.execute (webdriver\node_modules\phantom\lib\phantom.js:238:25)
    at Phantom.exit (webdriver\node_modules\phantom\lib\phantom.js:303:18)
    at PhantomDriver.dispose (webdriver\phantomdriver.js:26:38)
    at Singleton (webdriver\index.js:40:15)
    at Timeout.setTimeout (webdriver\singleton.js:42:16)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

### Steps to reproduce the behavior

1. Call `phantom.create(['--webdriver=localhost:8910'])` to create a new instance, namely `instance`
2. Call `instance.exit()`
3. Call `phantom.create(['--webdriver=localhost:8910'])` to create another instance, namely `instance2`
4. Call `instance2.exit()`

### Environment

- OS: Windows 10
- Node version (`node -v`): 6.1.0
- package version: 2.1.9

**Comment by compulim** [comment]
Because I am using GhostDriver, PhantomJS.exe don't get killed. I will use `phantomInstance.process.kill()` to shut it down immediately. So the bug no longer exists in this scenario.
