### ISSUE TITLE
SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by Viltaria** [amir20/phantomjs-node#613]
### Expected behavior

Expected constructor to work

### Actual behavior

Code errors out in constructor

### Steps to reproduce the behavior

```
    constructor(args = [], { phantomPath = _phantomjsPrebuilt2.default.path, logger = defaultLogger, logLevel = defaultLogLevel } = {
                     ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)

```

### Environment

- OS: Linux Ubuntu 16.04
- Node version (`node -v`): v4.2.6
- package version: ^4.0.0

**Comment by amir20** [comment]
Search the issues. Node version 6 and up is required for new version of phantom. 

Sent via my iPhone

**Comment by amir20** [comment]
Duplicate #602

**Comment by Viltaria** [comment]
Thanks!
