### ISSUE TITLE
JSON parse error?

### ISSUE THREAD

**Issue by Sajam** [amir20/phantomjs-node#620]
Hi,

I use this package to render some HTML. I got the following error (that I can't explain how it may happen?):

```
html_render_1   | Start rendering...
html_render_1   | undefined:1
html_render_1   | {"id":140,"target":"page$136","name":"invokeMethod","params":["renderBase64"],"deferred":null,"response":"iVBORw0KGgoAAAANSUhEUgAAAoAAACA+CAYAAAB0L5OTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAgAElEQVR4nOydeZwVxdnvf1XdfZbZN2aG2ZgZBpiFZUCWERQURQQUEFxQcUtUfGPco4kxRqJXr3o1uTH3dUti9NW8iXGJIKhoCGoiAqJEdkGWYYcZBmY5Z87SXXX/6K6mz2EAE3yDOM/384GZM91dXVuf+tXzPFUNEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEATx7SM1NbXg3HPPnT927NgXjzOprMsuu2wrAGPYsGH3z5w5czcANDQ0PH755ZdvP+6MngD69+9/88SJE98tLS2dnHyssLBw+CWXXLKupqbmuycib18XV1999fP/zPnnnXfeooKCghHHc8/S0tJzzjnnnDeOJw0AKCsrGzdz5sxdpaWl4483LYIgCIL4VlJbW3vD1KlTl9TW1t5w9dVXtw4ZMuSes846649nnHHG82VlZePOPPPMl473Hrm5ucPU71dcccUe51fj8ssv33G8aSeTkZFR5RFmev/+/W/+OtPPzc0dNnLkyF8C8APQ1N9ramquBZABAMOHD3/Q+XzSkiwAc3JyaqdNm/bZ1KlTl2RnZ/cHgLq6uhsvv/zy7aWlpePz8/MHwa6T4yEtNze35jjTAACceeaZL5WUlJz7daRFEMQ3B36iM0AQ3xZisVjHggULLlq7du3T
html_render_1   | 
html_render_1   | SyntaxError: Unexpected end of JSON input
html_render_1   |     at Object.parse (native)
html_render_1   |     at Stream.Phantom.process.stdout.pipe.on.data (/node_modules/phantom/lib/phantom.js:127:41)
html_render_1   |     at emitOne (events.js:96:13)
html_render_1   |     at Stream.emit (events.js:188:7)
html_render_1   |     at drain (/node_modules/through/index.js:36:16)
html_render_1   |     at Stream.stream.queue.stream.push (/node_modules/through/index.js:45:5)
html_render_1   |     at emit (/node_modules/split/index.js:37:14)
html_render_1   |     at Stream.<anonymous> (/node_modules/split/index.js:60:7)
html_render_1   |     at _end (/node_modules/through/index.js:65:9)
html_render_1   |     at Stream.stream.end (/node_modules/through/index.js:74:5)
```

#### Environment

- OS: Linux Mint 18.1 Cinnamon 64-bit
- `node -v`: v6.9.5
- package: 4.0.0

Any help/ideas would be awesome!

Thanks,
Daniel

**Comment by amir20** [comment]
I haven't seen this error before. Do you have some code that I can run locally to reproduce? I am assuming it is specific to your use case.

**Comment by Sajam** [comment]
Hello,

Thanks for your response and sorry for the issue. Most likely - it was caused by lack of memory on the server. For anyone that will be experiencing this in the future - remember to `.close()` you webpage instance and `.exit()` your phantom instance after job is done!

Thanks,
Daniel
