### ISSUE TITLE
Got error SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by cuongsimplypost** [amir20/phantomjs-node#634]
I'm using phantom with node v6.0.0. Recently, I got the error when trying render a pdf on testing environment. In my local machine, the problem isn't happen

Here is error stack: 
[SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at Liner.<anonymous> (/home/jenkins/build/workspace/bungee_dev/node_modules/phantom/lib/phantom.js:144:36)
    at emitOne (events.js:96:13)
    at Liner.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Liner.Readable.push (_stream_readable.js:130:10)
    at Liner.Transform.push (_stream_transform.js:128:32)
    at Liner.flush [as _flush] (/home/jenkins/build/workspace/bungee_dev/node_modules/linerstream/index.js:26:10)
    at Liner.<anonymous> (_stream_transform.js:118:12)
    at Liner.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at Liner.emit (events.js:185:7)
    at prefinish (_stream_writable.js:477:12)
    at finishMaybe (_stream_writable.js:485:7)
    at endWritable (_stream_writable.js:497:3)
    at Liner.Writable.end (_stream_writable.js:462:5)
    at Socket.onend (_stream_readable.js:517:10)
    at Socket.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)](url)

Any advice and suggestions will be greatly appreciated !

- OS: Mac OSX
- Node version (`node -v`): 6.0.0
- package version: 2.1.21

**Comment by cuongsimplypost** [comment]
Wrong repo
