### ISSUE TITLE
Random crashes, Error reading from stdin: Error: read ECONNRESET

### ISSUE THREAD

**Issue by NarutoInstinct** [amir20/phantomjs-node#731]
### Expected behavior

I expect for Phantom to load my given url without any error, to fetch the content of it and to take a screenshot of it.

### Actual behavior

A lot of the time, my script does that perfectly fine. However, with my test script I noticed that out of 206 times trying to execute my script, it "randomly" errored 12 times. The error it shows me is the following: 

```
Error: Error reading from stdin: Error: read ECONNRESET
    at commands.forEach.command (nodejs-api/node_modules/phantom/lib/phantom.js:358:33)
    at Map.forEach (native)
    at Phantom.rejectAllCommands (/nodejs-api/node_modules/phantom/lib/phantom.js:355:19)
    at Phantom.kill (/nodejs-api/node_modules/phantom/lib/phantom.js:336:10)
    at Socket.Phantom.process.stdin.on.e (/nodejs-api/node_modules/phantom/lib/phantom.js:160:12)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

Currently I made it so that it simply attempts to open the page again under a new instance, which works fine but is obviously not ideal.

### Steps to reproduce the behavior

1. Make a file on a Debian server with the following code in it: https://hastebin.com/ewacodohej.js
(Or the following link for more debugging info: https://hastebin.com/uxozayafec.js)
2. Run the script with `node filename.js`
3. Let the script run for around 5-15 minutes. It happened to me once that it didn't error for the first 100-150 iterations, so patience is key. After some time it should give the error mentioned above.
### Environment

- OS:  Debian 3.16.51-3
- Node version (`node -v`): v8.6.0
- package version: 4.0.12

**Comment by amir20** [comment]
94% success is actually pretty good ;) So i did some googling and I found this [page](https://stackoverflow.com/questions/17245881/node-js-econnreset). This confirms what I had been thinking. `ECONNRESET` is when the remote socket is closed unexpectedly. There is nothing that phantomjs or node can do. The right approach is to wrap in `try-catch` again and retry.
