### ISSUE TITLE
phantom run start on Docker (Linux / Ubuntu) call Error: spawn Unknown system error -8

### ISSUE THREAD

**Issue by leowang15** [amir20/phantomjs-node#737]
### Expected behavior

When I start on Docker, phantom must be called : spawn Unknown system error -8

### Actual behavior

Error description：

{ Error: spawn Unknown system error -8
    at _errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:502:9)
    at new Phantom (/app/ws/node_modules/_phantom@4.0.12@phantom/lib/phantom.js:93:45)
    at resolve (/app/ws/node_modules/_phantom@4.0.12@phantom/lib/index.js:15:41)
    at new Promise (<anonymous>)
    at Object.create (/app/ws/node_modules/_phantom@4.0.12@phantom/lib/index.js:15:10)
    at createPdf (/app/ws/src/model/file/index.js:17:34)
    at Object.exports.exportPdfFiles (/app/ws/src/model/file/index.js:71:13)
    at /app/ws/src/controller/file/index.js:67:37
  code: 'Unknown system error -8',
  errno: 'Unknown system error -8',
  syscall: 'spawn' }

### Environment

- OS: Alpine Linux running in a Docker container (node:8:11.1-alpine)
- Node version (`node -v`):8.11.1
- package version: 0.0.1

Could you give me solution please.

**Comment by leowang15** [comment]
My Dockerfile:

FROM node:8.11.1-alpine

RUN apk update && apk add --no-cache fontconfig curl curl-dev && \
  mkdir -p /usr/share && \
  cd /usr/share \
  && curl -L https://github.com/Overbryd/docker-phantomjs-alpine/releases/download/2.11/phantomjs-alpine-x86_64.tar.bz2 | tar xj \
  && ln -s /usr/share/phantomjs/phantomjs /usr/bin/phantomjs \
  && phantomjs --version

**Comment by amir20** [comment]
There is a lot of dependeices you need to install. You can use [this file](https://github.com/amir20/phantomjs-node/blob/master/examples/Dockerfile) as an example. I don't know how to do it in Alpine.

**Comment by leowang15** [comment]
Thx I will try it.
