### ISSUE TITLE
createOutObject crashing when asked for a property

### ISSUE THREAD

**Issue by cegonzalv** [amir20/phantomjs-node#752]
### Expected behavior

_outObj.property("urls") returns the property I asssigned

### Actual behavior

_outObj.property("urls") returns an error: 

```
Error:

 undefined is not an object (evaluating 'objectSpace[command.target][command.params[0]]')
    at Stream.Phantom.process.stdout.pipe.on.data (...\node_modules\phantom\dist\phantom.js:141:31)
    at Stream.emit (events.js:182:13)
    at drain (...\node_modules\through\index.js:36:16)
    at Stream.stream.queue.stream.push (...\node_modules\through\index.js:45:5)
    at emit (...\node_modules\split\index.js:37:14)
    at next (...\node_modules\split\index.js:49:7)
    at Stream.<anonymous> (...\node_modules\split\index.js:54:5)
    at Stream.stream.write (...\node_modules\through\index.js:26:11)

```

### Steps to reproduce the behavior

Just trying to run the following code:

```
var _ph, _page, cookie, _outObj, regex = '^http(s)?://(www|ssl)\.google-analytics\.com.*',cookie;
  phantom
  .create(['--ignore-ssl-errors=yes', '--load-images=no'])
  .then(ph => {
    console.log("startSubscribe")
    _ph = ph;
    _outObj = _ph.createOutObject();
    _outObj.urls = [];
    return _ph.createPage();
  })
  .then(page => {
    _page = page;

    _page.setting("loadImages",false);
    _page.setting("resourceTimeout",4000);
    console.log("trying on resource")
    _page.on('onResourceRequested',true, function (requestData, networkRequest,_outObj, regex) {
      if (new RegExp(regex, 'ig').test(requestData.url)) {
        request.abort();
        _outObj.urls.push(requestData.url)
      }
    },_outObj, regex);
    _page.on("onConsoleMessage", function () {
                //ignore the trash coming from the page
            });
    _page.on("onError", function () {
      //ignore the trash coming from the page
    });                 
    _page.on("onAlert", function () {
      //ignore the trash coming from the page
    });    
    return _page.open('www.example.com');
  })
  
  .then( session => {
      console.log(urls);
      return _page.property('cookies');
  })
  .then(ck => {
    return _outObj.property('urls');
  })
```

I know the error is ocurring the index.js property function of the package, where you call this: 

` command.response = objectSpace[command.target][command.params[0]];`

### Environment

- OS: Windows 
- Node version (`node -v`): 10.1.0
- package version:  6.0.3

**Comment by amir20** [comment]
Yup, I can confirm this is a bug. I was able to reproduce it. :/ So much going on with my other projects. But I'll try to take look at it. I had initially deprecated `OutObject` so I hadn't really tested this. I think with `on` and deprecating `property` this is now broken. Is your use case to just return a list of URLs?

**Comment by cegonzalv** [comment]
Thanks! It's just that I would like to retrieve the list of urls that i have aborted when they match a certain condition. I'll let you know if I'm able to fix it myself
